version: "3"
services:
 yuker_rest:
  image: mhart/alpine-node:8
  container_name: yuker_rest
  restart: on-failure
  working_dir: /yuker
  command: npm start
  ports:
   - "3000:3000"
  volumes:
   - ./rest:/yuker
  links: 
   - mongo
  depends_on:
   - mongo
  networks:
   - network_yuker
 yuker_graphql:
  image: mhart/alpine-node:8
  container_name: yuker_graphql
  restart: on-failure
  working_dir: /yuker
  command: npm start
  ports:
   - "3001:3001"
  volumes:
   - ./graphql:/yuker
  links: 
   - 'mongo'
  depends_on:
   - 'mongo'
  networks:
   - network_yuker
 prometheus:
  image: prom/prometheus:v2.20.1
  container_name: prometheus_yuker
  volumes:
  - ./prometheus/:/etc/prometheus
  ports:
  - "9090:9090"
  depends_on:
  - yuker_rest
  links:
  - yuker_rest
  command: ["--config.file=/etc/prometheus/prometheus.yml"]
  networks:
  - network_yuker
 mongo:
  image: mvertes/alpine-mongo
  container_name: mongo_yuker
  ports:
   - "27018:27017"
  volumes:
   - /data/db
  networks:
   - network_yuker
 grafana:
  image: grafana/grafana:7.1.5
  container_name: grafana_yuker
  environment:
   - GF_DISABLE_LOGIN_FORM=true
   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
   - GF_AUTH_ANONYMOUS_ENABLED=true
   - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
  volumes:
   - myGrafanaVol:/var/lib/grafana
   - ./grafana/:/etc/grafana/provisioning/datasources/
  ports:
   - "3500:3000"
  depends_on:
   - prometheus
  links:
   - prometheus   
  networks:
   - network_yuker
volumes:
  myGrafanaVol: {}
networks:
  network_yuker:
 
